site_name: Harminder Singh Nijjar
site_url: https://harminder.dev
copyright: >
  Copyright &copy; 2024 Harminder Singh Nijjar – All rights reserved.
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress 
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.indexes # Useful for providing overview pages
    - toc.follow
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.share

extra:
  consent:
    title: Cookie consent
    description: >- 
      This site uses cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of the documentation and whether users
      find what they're searching for. With your consent, you're helping me make this
      website better for everyone.
  analytics:
    provider: google
    property: G-X0B1C5DM9K
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://discord.gg/cstaDPWghP" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/discord
      name: Discord
      link: https://discord.gg/nuJfCWCxby
    - icon: fontawesome/brands/youtube
      name: YouTube
      link: https://www.youtube.com/@harmindersinghnijjar
    - icon: fontawesome/brands/github
      name: GitHub
      link: https://github.com/harmindersinghnijjar
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/harmindersinghnijjar/
    

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocstrings
  - search
  - git-revision-date:
      enabled: false
  - privacy
  - social
  - blog:
      blog_toc: true
  - ultralytics:
      add_share_buttons: True
      add_authors: true
      add_json_ld: True
  - tags

