authors:
  harmindersinghnijjar:
    name: Harminder Singh Nijjar
    description: Software Engineer, Tech Enthusiast, Blogger
    avatar: https://avatars.githubusercontent.com/u/110620707?s=400&u=45c11307490634d26e2a876d0f823ff104d9b889&v=4